# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6881093da789c1051f7c1ee665e2bc95914a8f61065baeeef094464db37ef8670845aac0617e4dd1889e37b38d674db00a169f92d6ed976f1238d71fc12e3339

test:
  secret_key_base: ada204dd6205706d6bee9a2c848eab1e9aea5ea96013891ac9856316f790dcb49c62e6d6776fbe25e1b45bb992f25b17c3e211d5174cf1032e11d108ea811f36

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
